version: '3.5'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db-data:
    driver: local

services:
  web:
    image: nginx:1.21-alpine
    container_name: web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/local/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/local/nginx/ssl:/etc/nginx/ssl
      - ./:/var/www/html
    networks:
      - frontend
      - backend
    depends_on:
      - db
  app:
    build: ./docker/local/php-fpm
    container_name: app
    volumes:
      - ./:/var/www/html
      - ./docker/local/php-fpm/php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - 3306:3306
    # パスワードで mysql にログインできるようにする
    command: --authentication_policy=mysql_native_password
    # mbind: Operation not permitted が mysql エラーログに表示されないようにする対策
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=reinventing_the_wheel
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
      # タイムゾーンを 東京 にする
      - TZ=Asia/Tokyo
    volumes:
      - ./logs/db:/var/log/mysql
      - ./docker/local/mysql/etc-mysql.cnf:/etc/mysql/conf.d/etc-mysql.cnf
      - ./docker/local/mysql/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    networks:
      - backend
